### PR TITLE
added filename input

### PR DESCRIPTION
**Pull request by Dfmaaa**

### CODE REVIEW

**Comment by previouslyanywhere** [comment]
looks good, could you do the same thing in `audio.ipynb` file? I'll merge the request once you do it.

**Comment by Dfmaaa** [comment]
Sorry for answering late, I forgot to check github, I'll change the code today!

**Comment by Dfmaaa** [comment]
Hello, the audio.ipynb has no filename variable, should I create one? I'm sorry. I've never worked with jupyter notebook before

**Comment by previouslyanywhere** [comment]
Yes, you can create one, if jupyter notebook is too confusing for you, I'll take care of it and will merge your pull request tomorrow.

**Comment by Dfmaaa** [comment]
yes you do it i am too dumb

**Pull request merged**
